### 1. Data types and structures

#### 1.1. Basic data types

R is a _dynamically typed_ language, which means that the R interpreter infers the type of an object at runtime.

##### 1.1.1. Integer

**Integer** is a number that can be written without a fractional component. You can declare an **integer** by appending an L suffix. To assign a value to a variable, type the name of a variable followed by an assignment operator (__<-__ or **_=_**) followoed by the value:

In [9]:
var_int_1 <- 5L
var_int_1

[1] 5

In [27]:
var_int_1 = 6
var_int_1
typeof(var_int_1)

[1] 6

[1] "double"

**_Artithmetic Operators_**. You are already familiar with these, since they come from basic mathematics. The arithmetic operators are:

* addition (+);
* subtraction (-);
* multiplication (*);
* division (/);
* exponent (^ or **);
* floor division (%/%);
* modulus division (%%). 

The first five operators are straightforward. The 6th, floor division operator (%/%), returns a number without a fractional component, and the final, modulus division operator (%%), returns the remainder of division:

In [ ]:
2 + 1

In [ ]:
2 - 1

In [ ]:
2 * 2

In [ ]:
1 / 2

In [ ]:
2 ^ 3

In [ ]:
2 ** 3

In [17]:
5 %/% 2

[1] 2

In [12]:
5 %% 2

[1] 1

In [13]:
(5 %/% 2) * 2 + (5 %% 2)

[1] 5

If you want to increase the value of variable **var_int_1** by 10, you have to write **var_int_1 = var_int_1 + 10**, because R does not have **+=** operator.

In [22]:
var_int_1 = var_int_1 + 10L
var_int_1

[1] 16

The built-in function **typeof()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/typeof.html) provides type information for all objects, both built-in and newly created ones.

In [23]:
typeof(var_int_1)

[1] "integer"

In [ ]:
typeof(1 / 2)

##### 1.1.2. Double

The previous expression gives rise to the next basic data type, the **double** object. A default number in R is **double**, unless specifically declared as an **integer**:

In [28]:
var_double_1 = 1
typeof(var_double_1)

[1] "double"

In [29]:
var_double_1 + 1.0

[1] 2

**_Comparison operators_**. You can use _comparison_ operators to compare the values of variables. They will always return a logical (see next cell) value. There are six _comparison_ operators:

* Equal (==). Not the same as the assignment operator (=);
* Not equal (!=);
* Greater than (>);
* Less than (<);
* Greater than or equal (>=);
* Less than or equal (<=).

##### 1.1.3. Logical

**Logical** object is a binary data type, meaning it can take only 2 values, **TRUE** or **FALSE**. The following code shows R’s _comparison operators_ applied to numbers, with the resulting **logical** objects:

In [ ]:
2 == 1

In [ ]:
2 != 1

In [ ]:
2 > 1

In [ ]:
2 < 1

In [ ]:
2 >= 1

In [ ]:
2 <= 1

In [ ]:
typeof(2 > 1)

In [30]:
typeof(FALSE)

[1] "logical"

**_Logical Operators_**. A _logical operator_ is a symbol or word used to connect two or more expressions. _Logical operators_ are applied to **logical** objects, which in turn yields another **logical** object. The operators are: 

* **&** - will return **TRUE** if both operands are **TRUE**;
* **|** - will return **TRUE** if at least one operand is **TRUE**;
* **!** - will return **TRUE** if the operand is **FALSE** and vice-versa.

In [31]:
TRUE & TRUE

[1] TRUE

In [32]:
TRUE & FALSE

[1] FALSE

In [33]:
FALSE & FALSE

[1] FALSE

In [34]:
TRUE | TRUE

[1] TRUE

In [35]:
TRUE | FALSE

[1] TRUE

In [36]:
FALSE | FALSE

[1] FALSE

In [37]:
!TRUE

[1] FALSE

In [38]:
!FALSE

[1] TRUE

Of course, both types of operators (_comparison_ and _logical_) are often combined:

In [39]:
(2 > 1) & (3 > 4)

[1] FALSE

In [40]:
(2 == 1) | (3 != 4)

[1] TRUE

In [41]:
!(2 != 2)

[1] TRUE

In [42]:
(!(2 != 2)) & (3 == 1)

[1] FALSE

One major application is to control the code flow via other R keywords, such as **if** or **while** (to be discussed later):

In [43]:
if (2 > 1){
    print('Condition True')
    }

[1] "Condition True"


In [44]:
var_double_2 = 0  
while (var_double_2 < 3){
    print(   paste('Condition true, i =', var_double_2)   )  
    var_double_2 = var_double_2 + 1
    }

[1] "Condition true, i = 0"
[1] "Condition true, i = 1"
[1] "Condition true, i = 2"


Numerically, R attaches a value of 0 to **FALSE** and a value of 1 to **TRUE**, when transforming **logical** value to an **integer** using **as.integer()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/integer.html) function or to a **double** using **as.double()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/double.html) function. When transforming number to **logical** objects via the **as.logical()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/logical.html) function, a 0 gives **FALSE** while all other numbers give **TRUE**:

In [45]:
as.integer(TRUE)

[1] 1

In [46]:
as.integer(FALSE)

[1] 0

In [47]:
as.double(TRUE)

[1] 1

In [48]:
as.double(FALSE)

[1] 0

In [49]:
as.logical(0)

[1] FALSE

In [50]:
as.logical(1)

[1] TRUE

In [51]:
as.logical(10.5)

[1] TRUE

In [52]:
as.logical(-2)

[1] TRUE

##### 1.1.4. Character

The basic data type to represent text in R is **character**. A **character** object is generally defined by single ('text') or double ("text") quotation marks or by converting another object using the **as.character()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/character.html) function:

In [53]:
var_char_1 = 'this is a character object'
var_char_1

[1] "this is a character object"

In [54]:
var_int_2 = 1000
var_char_2 = as.character(var_int_2)
var_char_2

[1] "1000"

In [55]:
typeof(var_char_2)

[1] "character"

Sometimes it is useful to use **print()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/print.html) function to display objects:

In [57]:
print(var_char_2)
var_char_2

[1] "1000"


[1] "1000"

In [58]:
print(var_char_2, quote=FALSE)

[1] 1000


Since objects in R do not have methods, you have to use functions instead. You can, for example, capitalize all the letters in this object using **toupper()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/chartr.html) function:

In [59]:
toupper(var_char_1)

[1] "THIS IS A CHARACTER OBJECT"

Or you can split it into its single-word components using **strsplit()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/strsplit.html) function to get a **list** object of all the words (more on **list** objects later):

In [60]:
print(   strsplit(var_char_1, " ")   )

[[1]]
[1] "this"      "is"        "a"         "character" "object"   



In [61]:
print(   strsplit(var_char_1, "s")   )

[[1]]
[1] "thi"                 " i"                  " a character object"



In [62]:
typeof(   strsplit(var_char_1, "s")   )

[1] "list"

This example illustrates that functions can be used inside other functions. In this case **strsplit()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/strsplit.html) function is used inside **typeof()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/typeof.html) function.

Let's get back to **character** objects. You can also search for a word using **regexpr()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html) function and get the position (starting with 1) of the first letter of the word (position in R is also called an _index_):

In [63]:
regexpr('character', var_char_1)

[1] 11
attr(,"match.length")
[1] 9
attr(,"index.type")
[1] "chars"
attr(,"useBytes")
[1] TRUE

If the word is not in the **character** object, the method returns -1:

In [64]:
regexpr('Python', var_char_1)

[1] -1
attr(,"match.length")
[1] -1
attr(,"index.type")
[1] "chars"
attr(,"useBytes")
[1] TRUE

You can also view any portion of a **character** object using **substr()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/substr.html) function by providing starting and ending indices:

In [66]:
substr(var_char_1, 1, 6)

[1] "this i"

Or you can choose only one symbol:

In [67]:
substr(var_char_1, 12, 12)

[1] "h"

In R **character** objects can't be sliced using square brackets, but **list** objects can, so the discussion on slicing will be relegated to the section about lists.
The length of a **character** object can be found using **nchar()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/nchar.html) function:

In [68]:
nchar(var_char_1)

[1] 26

Replacing characters is easily accomplished with the **gsub()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/grep.html) function:

In [69]:
gsub(" ", " | ", var_char_1)

[1] "this | is | a | character | object"

The stripping of whitespaces can be done using **trimws()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/trimws.html) function:

In [70]:
var_char_3 = '   This is R! '
trimws(var_char_3)

[1] "This is R!"

You can print strings and variables together using **paste()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/paste.html), **cat()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/cat.html) or **message()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/message.html) functions:

In [73]:
var_double_3 = 1.5
paste('One and a half', var_double_3)

[1] "One and a half 1.5"

In [74]:
cat(var_double_3, 'one and a half. Two and a half', (var_double_3 + 1))

1.5 one and a half. Two and a half 2.5

In [75]:
message(var_double_3, ' one and a half.')

1.5 one and a half.


String replacements are particularly useful in the context of multiple printing operations where the printed data is updated, for instance, during a **while** loop:

In [76]:
var_double_4 = 0

while (var_double_4 < 3){
    print(paste('Condition true, i = ', var_double_4))
    var_double_4 = var_double_4 + 1
}

[1] "Condition true, i =  0"
[1] "Condition true, i =  1"
[1] "Condition true, i =  2"


##### 1.1.5. Complex

In R there is another data type, **complex** object, but we will not be talking about it here:

In [77]:
var_complex_1 = 1+4i
typeof(var_complex_1)

[1] "complex"

**_Exercises:_**

Exercise 1. What values of **var_int** will return **FALSE** in the following expression?

In [78]:
var_int = 5
((5 != 4) & (2 <= 1)) | (!(1 == var_int) & (8 >= 8))

[1] TRUE

Exercise 2. Remove all occurences of 'th' from a sentence 'this is another character object'.

In [79]:
text = 'this is another character object'
print(gsub('th',"",text))

[1] "is is anoer character object"


Exercise 3. Transform a number 56789 into 78 without using any arithmetic operators.

In [80]:
nb=56789
as.integer(substr(as.character(nb),3,4))

[1] 78

#### 1.2. Basic data structures

Data structures are objects that contain a number of other objects. R’s base data structures can be organised by their dimensionality (1-d, 2-d, or n-d) and whether they’re homogeneous (all elements of the same type) or heterogeneous (elements can be of different types). This gives rise to the five data types:

| Dimensions | Homogeneous | Hetergeneous |
| --- | --- | --- |
| 1-d | Vector | List |
| 2-d | Matrix | Data frame |
| n-d | Array | - |

Note that R has no 0-dimensional, or scalar types: individual numbers or strings, which you might think would be scalars, are actually **vectors** of length one.

##### 1.2.1. Vector

A **vector** is the most common and basic data structure in R and is pretty much the workhorse of R. A **vector** is a collection of elements of the same type: **character**, **logical**, **integer** or **double**.

You can create an empty **vector** with **vector()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/vector.html) function. By default the mode is **logical**, but you can use direct constructors such as **character()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/character.html), **double()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/double.html) etc.

In [1]:
var_vector_1 = vector()
print(var_vector_1)

logical(0)


In [2]:
var_vector_2 = vector('character', length=5)
print(var_vector_2)

[1] "" "" "" "" ""


In [3]:
var_vector_3 = double(5)
print(var_vector_3)

[1] 0 0 0 0 0


You can insert, change or add **vector** elements by referring to those elements using square brackets **[...]**:

In [7]:
var_vector_3[2] = 1
print(var_vector_3)

[1] 0 1 0 0 0


In [8]:
var_vector_3[6] = 9
print(var_vector_3)

[1] 0 1 0 0 0 9


In [9]:
var_vector_3[6] = var_vector_3[6] + 1
print(var_vector_3)

[1]  0  1  0  0  0 10


You can also create **vectors** by directly specifying their content using **c()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html) function. R will then guess the appropriate mode of storage for the **vector**:

In [10]:
var_vector_4 = c(1, 2, 3, 4)
print(var_vector_4)

[1] 1 2 3 4


In [11]:
typeof(var_vector_4)

[1] "double"

You can create **vectors** as a sequence of numbers using **seq()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/seq.html) function:

In [12]:
var_vector_5 = seq(10)
print(var_vector_5)

 [1]  1  2  3  4  5  6  7  8  9 10


In [13]:
var_vector_6 = seq(from=5, to=10, by=0.5)
print(var_vector_6)

 [1]  5.0  5.5  6.0  6.5  7.0  7.5  8.0  8.5  9.0  9.5 10.0


In [14]:
var_vector_7 = 5:10
print(var_vector_7)

[1]  5  6  7  8  9 10


Using quoted text will create a **vector** of type **character**:

In [15]:
var_vector_8 = c('John', 'Peter', 'Tom')
print(var_vector_8)

[1] "John"  "Peter" "Tom"  


In [16]:
typeof(var_vector_8)

[1] "character"

The functions **length()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/length.html) and **str()** (https://stat.ethz.ch/R-manual/R-devel/library/utils/html/str.html) provide useful information about your **vectors** and R objects in general.

In [17]:
length(var_vector_8)

[1] 3

In [19]:
str(var_vector_8)

 chr [1:3] "John" "Peter" "Tom"
[1] "John"


The function **c()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html) can also be used to add elements to a **vector**:

In [20]:
var_vector_9 = c(var_vector_8, 'Roman')
print(var_vector_9)

[1] "John"  "Peter" "Tom"   "Roman"


In [21]:
var_vector_10 = c('Martin', var_vector_9)
print(var_vector_10)

[1] "Martin" "John"   "Peter"  "Tom"    "Roman" 


You can see that **vectors** are always flat, even if you nest **c()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html):

In [22]:
var_vector_11 = c(1, c(2, c(3, 4)))
print(var_vector_11)

[1] 1 2 3 4


If mixing types inside a **vector**, R will create a resulting **vector** with a mode that can most easily accommodate all the elements it contains. This conversion between modes of storage is called _coercion_. When R converts the mode of storage based on its content, it is referred to as _implicit coercion_. For instance:

In [23]:
var_vector_12 = c(100, 'hundred')
print(var_vector_12)

[1] "100"     "hundred"


In [24]:
typeof(var_vector_12)

[1] "character"

In [25]:
var_vector_13 = c(TRUE, 2)
print(var_vector_13)

[1] 1 2


You can perform arithmetic operations on **vectors** and between them:

In [27]:
var_vector_14 = 1:5
print(   var_vector_14 ^ 2   )

[1]  1  4  9 16 25


In [28]:
print(   var_vector_14 + var_vector_14   )

[1]  2  4  6  8 10


Note: **vectors** will be discussed in more detail in section 3.

##### 1.2.2. Matrix

In R a **matrix** is an extension of a **vector**. It is not a separate type of object but simply a **vector** with dimensions - with the number of rows and columns. As with **vectors**, the elements of a **matrix** must be of the same data type. **Matrix** can be created using **matrix()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/matrix.html) function:

In [29]:
var_matrix_1 = matrix(nrow=3, ncol=3)
print(var_matrix_1)

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   NA   NA   NA


You can check or set the dimensions of a **matrix** using **dim()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/dim.html) function:

In [33]:
var_matrix_2 = 1:12
dim(var_matrix_2) = c(3, 4)
print(var_matrix_2)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


As you can see, in R **matrices** are filled column-wise. Another way to create a **matrix** is to enter the data and dimensions right away:

In [35]:
var_matrix_3 = matrix(1:8, nrow=4, ncol=2)
print(var_matrix_3)

     [,1] [,2]
[1,]    1    5
[2,]    2    6
[3,]    3    7
[4,]    4    8


You can choose or change a value or a **vector** by referring to it using square brackets **[...]**:

In [37]:
var_matrix_3[1, 2] = 10
print(var_matrix_3)

     [,1] [,2]
[1,]    1   10
[2,]    2   10
[3,]    3    7
[4,]    4    8


In [38]:
var_matrix_3[4,] = c(20, 40)
print(var_matrix_3)

     [,1] [,2]
[1,]    1   10
[2,]    2   10
[3,]    3    7
[4,]   20   40


In [39]:
var_matrix_3[,2] = var_matrix_3[,2] * 2
print(var_matrix_3)

     [,1] [,2]
[1,]    1   20
[2,]    2   20
[3,]    3   14
[4,]   20   80


You can transpose a **matrix** using **t()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/t.html) function:

In [40]:
print(   t(var_matrix_3)   )

     [,1] [,2] [,3] [,4]
[1,]    1    2    3   20
[2,]   20   20   14   80


You can perform arithmetic opertions on **matrices** and between them:

In [41]:
var_matrix_4 = matrix(1:9, nrow = 3)
print(   var_matrix_4 ^ 2   )

     [,1] [,2] [,3]
[1,]    1   16   49
[2,]    4   25   64
[3,]    9   36   81


In [42]:
print(   var_matrix_4 + var_matrix_4   )

     [,1] [,2] [,3]
[1,]    2    8   14
[2,]    4   10   16
[3,]    6   12   18


Note: **matrices** will be discussed in more detail in section 3.

A **vector** or a **matrix** can only contain elements of the same type. Another object, a **list**, can contain various types.

##### 1.2.3. List

In R **lists** act as containers. Unlike **vectors**, the contents of a **list** are not restricted to a single mode and can encompass any mixture of data types. Create **lists** using **list()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.html) functon:

In [43]:
var_list_1 = list(1:3, "hi", c(TRUE, FALSE), c(0.5, -1.9))
print(var_list_1)

[[1]]
[1] 1 2 3

[[2]]
[1] "hi"

[[3]]
[1]  TRUE FALSE

[[4]]
[1]  0.5 -1.9



In [44]:
str(var_list_1)

List of 4
 $ : int [1:3] 1 2 3
 $ : chr "hi"
 $ : logi [1:2] TRUE FALSE
 $ : num [1:2] 0.5 -1.9


In [45]:
typeof(var_list_1)

[1] "list"

**Lists** are sometimes called recursive **vectors**, because a **list** can contain other **lists**. This makes them fundamentally different from **vectors**:

In [46]:
var_list_2 = list(1, list(2, list(3)))
print(var_list_2)

[[1]]
[1] 1

[[2]]
[[2]][[1]]
[1] 2

[[2]][[2]]
[[2]][[2]][[1]]
[1] 3





In [48]:
str(var_list_2)

List of 2
 $ : num 1
 $ :List of 2
  ..$ : num 2
  ..$ :List of 1
  .. ..$ : num 3


**c()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html) will combine several **lists** into one. Compare the results of **list()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/list.html) and **c()**:

In [50]:
var_list_3 = list(list(1, 2), c(3, 4))
print(var_list_3)
str(var_list_3)

[[1]]
[[1]][[1]]
[1] 1

[[1]][[2]]
[1] 2


[[2]]
[1] 3 4

List of 2
 $ :List of 2
  ..$ : num 1
  ..$ : num 2
 $ : num [1:2] 3 4


In [52]:
var_list_4 = c(list(1, 2), c(3, 4))
print(var_list_4)
str(var_list_4)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

List of 4
 $ : num 1
 $ : num 2
 $ : num 3
 $ : num 4


You can turn a **list** into a **vector** with **unlist()** (https://stat.ethz.ch/R-manual/R-patched/library/base/html/unlist.html) function. If the elements of a **list** have different types, **unlist()** uses the same coercion rules as **c()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/c.html):

In [54]:
var_list_5 = unlist(var_list_3)
print(var_list_5)
str(var_list_5)

[1] 1 2 3 4
 num [1:4] 1 2 3 4


You can choose elements from a **list** using double square brackets **[[...]]**:

In [55]:
print(var_list_1)

[[1]]
[1] 1 2 3

[[2]]
[1] "hi"

[[3]]
[1]  TRUE FALSE

[[4]]
[1]  0.5 -1.9



In [56]:
print(   var_list_1[[1]]   )

[1] 1 2 3


In [57]:
print(   var_list_1[[3]][1]   )

[1] TRUE


In [58]:
print(   var_list_1[c(1, 3)]   )

[[1]]
[1] 1 2 3

[[2]]
[1]  TRUE FALSE



In [59]:
print(   var_list_1[2:4]   )

[[1]]
[1] "hi"

[[2]]
[1]  TRUE FALSE

[[3]]
[1]  0.5 -1.9



You can add, remove or change elements in a **list**:

In [60]:
var_list_1[[3]] = NULL
print(var_list_1)

[[1]]
[1] 1 2 3

[[2]]
[1] "hi"

[[3]]
[1]  0.5 -1.9



In [61]:
var_list_1[[4]] = matrix(1:6, nrow=3)
var_list_1[[3]][1] = 1.5
print(var_list_1)

[[1]]
[1] 1 2 3

[[2]]
[1] "hi"

[[3]]
[1]  1.5 -1.9

[[4]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



You can also remove an element by providing an index with a negative sign:

In [62]:
var_list_6 = var_list_1[-2]
print(var_list_6)

[[1]]
[1] 1 2 3

[[2]]
[1]  1.5 -1.9

[[3]]
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



You can name the elements of a **list** using **names()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/names.html) function:

In [63]:
names(var_list_1) = c('integer', 'char', 'double', 'matrix')
print(var_list_1)

$integer
[1] 1 2 3

$char
[1] "hi"

$double
[1]  1.5 -1.9

$matrix
     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



In [64]:
print(   var_list_1$matrix   )

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


Another data structure in R that can encompass a mixture of datatypes is the **data frame**.

##### 1.2.4. Data frame

A **data frame** is a very important data type in R. It’s very useful for most tabular data and for statistics. A **data frame** is a special type of a **list** where every element of the **list** has same length (i.e. **data frame** is a _rectangular_ **list**). **Data frames** are usually imported, but can also be created by hand using **data.frame()** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/data.frame.html) function:

In [65]:
var_data_1 = data.frame(Letter=letters[1:10], First=0:9, Second=10:19)
var_data_1

Letter First Second
1  a      0     10    
2  b      1     11    
3  c      2     12    
4  d      3     13    
5  e      4     14    
6  f      5     15    
7  g      6     16    
8  h      7     17    
9  i      8     18    
10 j      9     19

Because **data frames** are rectangular, elements of a **data frame** can be referenced by specifying the row and the column _index_ in single square brackets **[...]**:

In [66]:
var_data_1[5, 3]

[1] 14

As **data frames** are also **lists**, it is possible to refer to columns (which are elements of such **list**) using the **list** notation:

In [69]:
print(   var_data_1[[2]]   )

 [1] 0 1 2 3 4 5 6 7 8 9


In [70]:
print(   var_data_1[['First']]   )

 [1] 0 1 2 3 4 5 6 7 8 9


In [71]:
print(   var_data_1$Second   )

 [1] 10 11 12 13 14 15 16 17 18 19


Note: **data frames** will be discussed in more detail in section 4.

Finally, in R **for** loop can loop over a **list**, a **vector** a **matrix** and even a **data frame**:

In [72]:
for (i in c(1,3,8)) print(i)

[1] 1
[1] 3
[1] 8


In [74]:
var_matrix_5 = matrix(1:9, nrow=3, ncol=3)
for (i in var_matrix_5) print(i)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


In [75]:
var_list_7 = list('Hello', TRUE, 10, var_matrix_5)
for (i in var_list_7) print(i)

[1] "Hello"
[1] TRUE
[1] 10
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [76]:
for (i in var_data_1) print(i)

 [1] a b c d e f g h i j
Levels: a b c d e f g h i j
 [1] 0 1 2 3 4 5 6 7 8 9
 [1] 10 11 12 13 14 15 16 17 18 19


Note: **for** loops will be discussed in more detail in section 2.

**_Exercises:_**

Exercise 4. Using **for** loop, print the following numbers: 225, 169, 121, 81, 49, 25, 9, 1, 1, 9.

In [80]:
for (i in seq(15,-3,-2) )
print(i**2)

[1] 225
[1] 169
[1] 121
[1] 81
[1] 49
[1] 25
[1] 9
[1] 1
[1] 1
[1] 9


Exercise 5. Create a **list** containing numbers from exercise 5.

In [82]:
print(list(seq(15,-3,-2)**2))

[[1]]
 [1] 225 169 121  81  49  25   9   1   1   9



Exercise 6. Create a **list** with your name, age and country of origin. Introduce yourself:

In [87]:
my_info = list('Thomas SADURNI','22', 'France')
names(my_info) = c('Name','Age','Country')
print(my_info)
cat('My name is', my_info$Name,'I am',my_info$Age, 'and I am from', my_info$Country)

$Name
[1] "Thomas SADURNI"

$Age
[1] "22"

$Country
[1] "France"

My name is Thomas SADURNI I am 22 and I am from France

Exercise 7. You and your friend hold following stock portfolios. Display only the stocks that you both hold in common. Use **set** (https://stat.ethz.ch/R-manual/R-devel/library/base/html/sets.html) operations.

In [88]:
your_stocks = c('AAPL', 'GE', 'TSLA', 'UAL', 'BAC')
friends_stocks = c('FB', 'MSFT', 'AAL', 'TSLA', 'GE')

print(intersect(your_stocks,friends_stocks))

[1] "GE"   "TSLA"


Exercise 8. Display a **list** containing element by element product of (5, 6, 7) and (2, 0.5, 3) **vector** objects.

In [92]:
var_1 = 5:7
var_2 = c(2, 0.5, 3)
print(list(var_1*var_2))

var_1 %*% var_2

[[1]]
[1] 10  3 21

